[profile.default]
via_ir = true
solc = "0.8.22"

[rpc_endpoints]
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
ethereum_mainnet = "${ETHEREUM_MAINNET_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
arbitrum_mainnet = "${ARBITRUM_MAINNET_RPC_URL}"

[etherscan]
ethereum_mainnet = { key = "${ETHERSCAN_API_KEY}" }
ethereum_sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum_mainnet = { key = "${ARBISCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = 'https://api-sepolia.arbiscan.io/api' }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
