[profile.default]
via_ir = true
solc = "0.8.22"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum_one = "${ARBITRUM_ONE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_one_sepolia = "${ARBITRUM_ONE_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum_one = { key = "${ARBISCAN_API_KEY}" }
arbitrum_one_sepolia = { key = "${ARBISCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
